spring.application.name=demo

# =========================
# PostgreSQL
# =========================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/memberdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update

# =========================
# 初期管理者
# =========================

app.initial-admin.username=${INITIAL_ADMIN_USERNAME:admin}
app.initial-admin.password=${INITIAL_ADMIN_PASSWORD}

# =========================
# Server
# =========================

server.port=${PORT:8080}