spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/memberdb
spring.datasource.username=postgres
spring.datasource.password=syuu1219
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# 初期管理者
app.initial-admin.username=${INITIAL_ADMIN_USERNAME:admin}
app.initial-admin.password=${INITIAL_ADMIN_PASSWORD:password}